import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/StyledComponentsRegistry";
import { CustomThemeProvider } from "@/context/ThemeContext";
import ThemeWrapper from "@/lib/ThemeWrapper";
import Header from "@/components/Header/Header";
import { ReactQueryProvider } from "@/context/ReactQueryProvider";

const beVietnamPro = Be_Vietnam_Pro({
	weight: ["300", "500", "600"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Unsplash Collection",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={beVietnamPro.className}>
				<ReactQueryProvider>
					<StyledComponentsRegistry>
						<CustomThemeProvider>
							<ThemeWrapper>
								<Header />
								{children}
							</ThemeWrapper>
						</CustomThemeProvider>
					</StyledComponentsRegistry>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
